---
title: "PPOL-564-Project-Proposal"
author: "Merykokeb Belay"
date: "10/25/2020"
output: html_document
---
### Overview
The goal of this analysis is to collect COVID-19 race and ethnicity data and assess which states have the highest reported infections by race and also the lowest by share of population. Additionally, using data quantifying states’ efforts to maintain and expand the Affordable Care Act, this project will examine if there is a relationship between a states’ effort to maintain the Affordable Care Act and the reported number of cases and deaths by race and ethnicity. According to data collected the The COVID Data Project, people of color are disproportionately affected by the COVID-19 pandemic: “nationwide, Black people are dying at 2.2 times the rate of white people (3)”. Additionally, “ Are states with higher rates of cases and deaths amongst racial minorities also states who have put in the least effort to expand and maintain ACA? Characterize states by % enrolled in ACA; percent uninsured; Identify states where percent of cases and deaths is greater than population percent

### Data Sources
The COVID Racial Data tracker is a collaborative project between The Atlantic’s ‘The COVID Tracking Project’ and Center for Antiracist Research at Boston University. The COVID Racial Data Tracker, launched on April 12, 2020, collects the most up-to-date racial demographic data on COVID-19 related metrics (3). In an effort to show the racial disparities in the number of cases and deaths reported by states, the people behind this Tracker have also created a Racial Data Dashboard, which provides information on the total number of cases and deaths for each state that provides race and ethnicity figures for these metrics. There are currently 51 states/territories reporting positive cases and 50 states/territories reporting deaths (3). It is updated twice a week, using publicly available data from each state's Health Department. This data behind the dashboard, which is freely available on the Tracking Project’s website,  will be the primary source of data for this project. 

In addition to the Data Tracker, the project will make use of data tracking the extent to which states have exerted effort to maintain and expand the Affordable Care Act. Healthinsurance.org is a website that routinely provides up-to-date information on all things related to health insurance and health policy in the United States. One of their blog entries from June 2019, provides an in-depth analysis of what each state is doing to preserve the Affordable Care Act. As part of this blog, a PDF is freely available--this PDF works almost like a score-card, tracking  which provisions of the Affordable Care Act each state has been working to preserve and providing a ranking of sorts. This will serve as the secondary source of data for this project. 

Lastly, ACS data will be used to obtain population data by race and ethnicity for each state and territory in the Race Data Tracking sheet. There will also be a variable identifying the region (Northeast; West; South; Midwest) of each state

Data Collection Plan
The raw data used to build and update The COVID Racial Data Tracker is available in CSV format. This data will be collected by simply downloading the CSV file. Conversely, the pdf on the healthinsurance.org website will be obtained by scraping the table from the pdf. The ACS data will also be scraped.

### Methods 
Web scraping:  the BeautifulSoup (2) package will be used to obtain the data mentioned above, the web scraping methods learned in class will be employed. 
Data wrangling: pandas data frame (1) will be the primary tool used to manipulate the data sets into a version that can be accurately visualized and analyzed. 
Changing unit of observation: the current of observation for the data tracker is ‘date’. The data will instead be grouped by state; state names will be converted from two letter codes to their full name using the us_state_abbrev.py python dictionary (4). Additionally, data for the latest aggregate covid data report will be kept; all other data from previous days will be dropped. Column titles will be renamed. Downloaded and scraped tables will have columns renamed; unit of observations will be changed currently the table in the pdf is organized in a way where the provisions under the Affordable Care Act are the units of observation. Again groupby/pivot_tables will be used. Therefore, after scraping the table and getting the contents into a pandas dataframe, the unit of observation will be changed to state, the provision will instead take the current position of the states in the pdf. Additionally, the tally at the very last row of the pdf will also be its own column so as to create a row-based sum. For the covid-19 data tracker, the state names are currently in . 
Data visualization: Prepare a series of plots to depict the story behind the data collected and analyzed in a compelling way. Both plotline and matplotlib will be used to create visualizations. Graphs will depict aggregate total number of cases by ethnicity for all states that have provided data. Additionally there will be Graph depicting share of population by race and ethnicity and share of positive COVID-19 cases by race and ethnicity. With regards to the ACA data, there will graphs depicting provisions with the highest number of states passing legislature to keep. Also depict the variation of Start by depicting the share of racial minorities as a percentage of total population graphically. 
Machine (statistical) learning component: this project will use the data compiled and prepared to create a model assessing the relationship between states' perceptions of ACA and racial disparities in COVID-19 cases and deaths.

### Defining Success
Success for this project revolves around getting sufficient experience applying the lessons from class to working with real-life data. Particularly around create compelling visualization that displays the disparities by a simple view of the graph. 
